Pyfunceble not staging
[master d4774ca] My Privacy DNS Firewall - AutoSave
 35 files changed, 15437 insertions(+), 6472 deletions(-)
 create mode 100644 active_domains/output/__pyfunceble_loggging__/critical.log
 create mode 100644 active_domains/output/__pyfunceble_loggging__/debug.log
 create mode 100644 active_domains/output/__pyfunceble_loggging__/error.log
 create mode 100644 active_domains/output/__pyfunceble_loggging__/fatal.log
 create mode 100644 active_domains/output/__pyfunceble_loggging__/info.log
 create mode 100644 active_domains/output/__pyfunceble_loggging__/warning.log
Already on 'master'
M	active_domains/output/__pyfunceble_loggging__/info.log
From https://github.com/mypdns/porn-records
   f05f994..654506b  master     -> origin/master
error: cannot rebase: You have unstaged changes.
error: Please commit or stash them.
To https://github.com/mypdns/porn-records
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/mypdns/porn-records'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.